name: Django Testing CI

  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

  
  jobs:    
    build:


      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install ependencies
        run: |
          python -m pip install --upgrade pip
          python install -r requirements.txt
      - name: Check code quality
        run: |
          flake8
      - name: Run Tests
        run: |
          coverage run manage.py test
          coverage report


